# Generated by Django 4.2.4 on 2023-09-09 17:50

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channel",
            options={"verbose_name": " Channel"},
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True, null=True, upload_to=server.models.category_upload_path
            ),
        ),
        migrations.AlterUniqueTogether(
            name="channel",
            unique_together={("name", "server")},
        ),
    ]
