# Generated by Django 4.2.4 on 2023-09-10 05:39

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0003_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=server.models.channer_banner_upload_path,
            ),
        ),
    ]
