# Generated by Django 4.2.4 on 2023-09-10 06:11

from django.db import migrations, models
import server.models
import server.validators


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0004_channel_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=server.models.channer_banner_upload_path,
                validators=[server.validators.validate_image_icon_size],
            ),
        ),
    ]
